# Generated by Django 6.0.3 on 2026-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='achievements/')),
                ('date_awarded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyNewspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month_year', models.DateField(help_text='Select any day in the month')),
                ('pdf_file', models.FileField(upload_to='newspapers/')),
                ('cover_image', models.ImageField(blank=True, upload_to='newspaper_covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
